apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-fluentbit-sidecar-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Parsers_File  parsers.conf
    [INPUT]
        Name          tail
        Path          /opt/softwareag/IntegrationServer/logs/esb_trx.log
        Tag           webmethods.is
        Parser        json_log
        Refresh_Interval 5
        DB            /fluentbit-state/fluentbit_tail.db
        Buffer_Chunk_Size 2MB
        Buffer_Max_Size   15MB
    [FILTER]
        Name          record_modifier
        Match         webmethods.is
        Record        pod_name {{ .Release.Name }}
        Record        env {{ .Values.env | default "dev" }}
    [OUTPUT]
        Name          es
        Match         webmethods.is
        Host          {{ .Values.elasticsearch.host }}
        Port          {{ .Values.elasticsearch.port | default 9200 }}
        {{- if .Values.elasticsearch.username }}
        HTTP_User     {{ .Values.elasticsearch.username }}
        HTTP_Passwd   {{ .Values.elasticsearch.password }}
        {{- end }}
        Index         is-msr-logs
        Suppress_Type_Name On
        tls           {{ .Values.elasticsearch.tls | default "Off" }}
        Retry_Limit   False
  parsers.conf: |
    [PARSER]
        Name        json_log
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z